#!/bin/bash
# Quick setup script for AR Studio Cloudflare backend

set -e

echo "🚀 AR Studio - Cloudflare Backend Setup"
echo "========================================"
echo ""

# Check if wrangler is installed
if ! command -v npx &> /dev/null; then
    echo "❌ Error: npm/npx not found. Please install Node.js first."
    exit 1
fi

echo "✅ Node.js and npm found"
echo ""

# Install dependencies
echo "📦 Installing dependencies..."
npm install
echo "✅ Dependencies installed"
echo ""

# Login to Cloudflare
echo "🔐 Logging in to Cloudflare..."
echo "   (This will open a browser window)"
npx wrangler login
echo "✅ Logged in to Cloudflare"
echo ""

# Create D1 Database
echo "🗄️  Creating D1 Database..."
DB_OUTPUT=$(npx wrangler d1 create ar-studio-db 2>&1)
echo "$DB_OUTPUT"

# Extract database ID (this is a simple approach, might need adjustment)
DB_ID=$(echo "$DB_OUTPUT" | grep "database_id" | cut -d'"' -f2 | head -1)

if [ -z "$DB_ID" ]; then
    echo "⚠️  Could not automatically extract database ID."
    echo "   Please manually copy the database_id from the output above"
    echo "   and update it in wrangler.toml"
    echo ""
else
    echo "✅ Database created with ID: $DB_ID"
    
    # Update wrangler.toml with database ID
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s/database_id = \"placeholder-id\"/database_id = \"$DB_ID\"/" wrangler.toml
    else
        # Linux
        sed -i "s/database_id = \"placeholder-id\"/database_id = \"$DB_ID\"/" wrangler.toml
    fi
    echo "✅ Updated wrangler.toml with database ID"
fi
echo ""

# Create KV Namespace
echo "📦 Creating KV Namespace for assets..."
KV_OUTPUT=$(npx wrangler kv:namespace create "ASSETS" 2>&1)
echo "$KV_OUTPUT"

# Extract KV ID
KV_ID=$(echo "$KV_OUTPUT" | grep "id" | cut -d'"' -f2 | head -1)

if [ -z "$KV_ID" ]; then
    echo "⚠️  Could not automatically extract KV namespace ID."
    echo "   Please manually copy the id from the output above"
    echo "   and update it in wrangler.toml"
    echo ""
else
    echo "✅ KV Namespace created with ID: $KV_ID"
    
    # Update wrangler.toml with KV ID
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s/id = \"placeholder-id\"/id = \"$KV_ID\"/" wrangler.toml
    else
        # Linux
        sed -i "s/id = \"placeholder-id\"/id = \"$KV_ID\"/" wrangler.toml
    fi
    echo "✅ Updated wrangler.toml with KV namespace ID"
fi
echo ""

# Initialize database schema
echo "📊 Initializing database schema..."
npx wrangler d1 execute ar-studio-db --file=./schema.sql
echo "✅ Database schema initialized"
echo ""

# Deploy Worker
echo "🚀 Deploying Cloudflare Worker..."
DEPLOY_OUTPUT=$(npx wrangler deploy 2>&1)
echo "$DEPLOY_OUTPUT"

# Extract Worker URL
WORKER_URL=$(echo "$DEPLOY_OUTPUT" | grep -o "https://[a-zA-Z0-9-]*\.workers\.dev" | head -1)

if [ -z "$WORKER_URL" ]; then
    echo "⚠️  Could not automatically extract Worker URL."
    echo "   Please check the deployment output above for your Worker URL"
    echo ""
else
    echo ""
    echo "✅ Worker deployed successfully!"
    echo "🌐 Worker URL: $WORKER_URL"
    echo ""
    
    # Create config.js
    cat > config.js << EOF
/**
 * AR Studio Configuration
 * Auto-generated by setup script
 */

window.AR_STUDIO_CONFIG = {
  API_URL: '$WORKER_URL'
};
EOF
    
    echo "✅ Created config.js with Worker URL"
fi

echo ""
echo "=========================================="
echo "✨ Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Test the backend: curl $WORKER_URL/api/health"
echo "2. Push to GitHub (if not done already)"
echo "3. Enable GitHub Pages in repository settings"
echo "4. Open editor-cloud.html in your browser"
echo ""
echo "For more information, see:"
echo "- README.md"
echo "- CLOUDFLARE_SETUP.md"
echo "- DEPLOYMENT.md"
echo ""
echo "Happy AR creating! 🎉"
